import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { LoaderProvider } from "@/context/LoaderContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "PinDrop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/logo.png" type="image/png" />
        <title>PinDrop</title>

        <link rel="preload" as="image" href="/images/register-bg.jpg" />
      </head>
      <body
        className={`${poppins.variable} antialiased flex flex-col min-h-screen`}
      >
        <Provider>
          <LoaderProvider>{" "}
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer />
          </LoaderProvider>{" "}
        </Provider>
      </body>
    </html>
  );
}
